version: '3'

services:
  simcivil:
    image: simcivil
    build:
      context: .
      dockerfile: ./SimCivil.GateDockerfile

  orleans:
    image: orleans
    ports:
     - "30000:30000"
    build:
      context: .
      dockerfile: ./SimCivil.GateDockerfile
